// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_61pH9ijrskysvikbPh_X-8XXfvexsbU',
    appId: '1:576901217068:web:b13bf9fdec5ce607968a89',
    messagingSenderId: '576901217068',
    projectId: 'tchat-33d29',
    authDomain: 'tchat-33d29.firebaseapp.com',
    storageBucket: 'tchat-33d29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaacxXyXx9AEknweWCz6ayCPValoB_vt8',
    appId: '1:576901217068:android:ad3c57ae1228b1e5968a89',
    messagingSenderId: '576901217068',
    projectId: 'tchat-33d29',
    storageBucket: 'tchat-33d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MuVU-dbS_tWhK8AUXdl95YYxl2z6WAo',
    appId: '1:576901217068:ios:733928caf09e0c44968a89',
    messagingSenderId: '576901217068',
    projectId: 'tchat-33d29',
    storageBucket: 'tchat-33d29.appspot.com',
    iosClientId: '576901217068-mttib0q78b50p7tk742spoqkrh2kncar.apps.googleusercontent.com',
    iosBundleId: 'com.example.tchatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2MuVU-dbS_tWhK8AUXdl95YYxl2z6WAo',
    appId: '1:576901217068:ios:733928caf09e0c44968a89',
    messagingSenderId: '576901217068',
    projectId: 'tchat-33d29',
    storageBucket: 'tchat-33d29.appspot.com',
    iosClientId: '576901217068-mttib0q78b50p7tk742spoqkrh2kncar.apps.googleusercontent.com',
    iosBundleId: 'com.example.tchatFlutter',
  );
}
